export const PROJECT_FORM = 'PROJECT_FORM'
export const GET_PROJECTS = 'GET_PROJECTS'
export const ADD_PROJECT = 'ADD_PROJECT'
export const PROJECT_ERROR = 'PROJECT_ERROR'
export const SELECTED_PROJECT = 'SELECTED_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'

export const PROJECT_TASKS = 'PROJECT_TASKS'
export const ADD_TASK = 'ADD_TASK'
export const TASK_ERROR = 'TASK_ERROR'
export const DELETE_TASK = 'DELETE_TASK'
export const COMPLETED_TASK = 'COMPLETED_TASK'
export const SELECTED_TASK = 'SELECTED_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'


export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'